### ISSUE TITLE
pointing uberenv to existing spack

### ISSUE THREAD

**Issue by junkudo** [LLNL/uberenv#10]
Hey,
Is there a way to make uberenv use an existing spack installation without fetching?  I'd like to use uberenv in situations where I'm unable to fetch from github.
Thanks!
Jun

**Comment by cyrush** [comment]
@junkudo , we can certainly add support.

There are two pieces to the puzzle:  Using an existing spack install, but also using a mirror for the source tarballs, etc. 

We already have a mirror option, I suspect if you use the mirror option and then the `--prefix` option to point to a directory that has a spack install in it (--prefix=/path/to/mydir/, where /path/to/mydir/spack exists) may be close to what you want.
