### ISSUE TITLE
Support multiple package repos?

### ISSUE THREAD

**Issue by adayton1** [LLNL/uberenv#130]
I can't find a way to support pulling from multiple spack package repos (e.g. pick a package from my current repository, pick some other packages from radiuss-spack-configs, then finally pick any remaining packages from spack). Is there a way to do this? If not, could this feature be added? It seems like it would just come down to providing the path to the repos.yml file you want to use (not to be confused with the singular repo.yml file). See https://spack.readthedocs.io/en/latest/repositories.html#repos-yaml.

**Comment by white238** [comment]
https://github.com/LLNL/serac/blob/7672d330192aec5f4eb46ef48e0f5ec713b203f7/.uberenv_config.json#L9

**Comment by adayton1** [comment]
Thanks, @white238! The documentation does not mention that you can provide a list of multiple directories.

**Comment by adayton1** [comment]
Chris answered my question offline, but yes, it does match the order specified in repos.yml (packages from the right-most entry override packages from the entries to the left)
