### ISSUE TITLE
Fix read the docs

### ISSUE THREAD

**Issue by kennyweiss** [LLNL/uberenv#42]
Uberenv's read-the-docs has not updated in almost 2 years. 
See: https://uberenv.readthedocs.io

We should look into this and ensure that a new docs build is triggered on changes to uberenv.

We should also add a docs badge to uberenv's README.md

**Comment by cyrush** [comment]
FYI: I tried to manually build and I got an ambitious error that didn't lead me to anywhere.

**Comment by kennyweiss** [comment]
Bump -- looks like the docs haven't attempted to build since mid January -- https://readthedocs.org/projects/uberenv/builds/

Perhaps there's an issue w/ the RTD configuration?

**Comment by cyrush** [comment]
I was able to do a manual build. 
I don't see anything obvious --  want me to add you as admin?

**Comment by white238** [comment]
@cyrush fixed it.  Master/latest is now up to date. Formatting is less than ideal in many places
