### ISSUE TITLE
env path foward? spack install with yaml file on command line

### ISSUE THREAD

**Issue by cyrush** [LLNL/uberenv#81]
you can pass a yaml file with an environment spec directly to spack.

```
spack install ./spack.yaml
```

This path may open up a much easier way to use envs than spack shell support.

**Comment by cyrush** [comment]
@white238  FYI

**Comment by cyrush** [comment]
Or maybe I am just very confused -- simple example isn't working as I expected:

https://github.com/spack/spack/issues/31168

**Comment by adrienbernede** [comment]
I’d like to also bring this to your attention:
https://spack.readthedocs.io/en/latest/configuration.html?highlight=user_cache_path#overriding-local-configuration
I’ve add success that.

**Comment by cyrush** [comment]
Turns out I hopefully imagined or misunderstood this. 

You can't build envs by just handing them over on the command line. You do have to use the shell, or -e
