### ISSUE TITLE
add spack debug option

### ISSUE THREAD

**Issue by cyrush** [LLNL/uberenv#87]
When things go wrong in spack land, the first request from spack folks is the stack trace obtained with:

`spack --debug --stacktrace <command>`

We should have a `spack_debug` option that allows users to easily find this info vs hacking it in.

**Comment by chapman39** [comment]
Currently we only debug a couple of spack commands (`install` and `spec`). Thoughts on adding the following code to the `spack_exe()` function instead? @cyrush @white238 

```
debug = ""
if self.opts["spack_debug"]:
    debug = "--debug --stacktrace "
# Append debug to spack command
```

Otherwise this issue could probably be closed.
